# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: not-and
#subtitle: Hi! I'm Mariele and this is `not-and`, a place to register and share things I'm learning, or not.
email: mariele.f.motta@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
        a space for learning in the open
#excerpt: Test excerpt
#description: # >- # this means to ignore newlines until "baseurl:"

#{{ page.excerpt }}
#[^1]: Thanks to [Julia Evans's blog post!](https://jvns.ca/blog/2014/10/08/how-to-set-up-a-blog-in-5-minutes/)

baseurl: "/not-and" # the subpath of your site, e.g. /blog
url: "https://github.com/mfmotta" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MarieleMotta_
github_username:  mfmotta


navigation: 2

# Build settings
markdown: kramdown
redcarpet:
    extensions: [
        'footnotes',
        # 'no_intra_emphasis',
        # 'fenced_code_blocks',
        # 'autolink',
        # 'strikethrough',
        #'superscript',
        # 'with_toc_data',
        # 'tables',
        # 'hardwrap'
    ]
theme: minima
plugins:
- jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
